# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/assignment_db
spring.datasource.username=postgres
spring.datasource.password=yash
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Logging
logging.level.com.yash.virality_engine_api=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# CRON Schedule for testing (every 5 minutes)
# In production, change to 0 0/15 * * * * for 15 minutes